export const faq = [
  {
    slug: 'website-development',
    heading: 'Website Development',
    q1: 'Berapa besaran biaya pembuatan sebuah website untuk perusahaan B2B?',
    a1: 'Biaya pembuatan website B2B bergantung pada kompleksitas fitur, integrasi sistem, dan kebutuhan bisnis. Kami menyediakan konsultasi gratis untuk estimasi yang tepat.',
    q2: 'Apakah jasa website development sudah termasuk dengan optimasi SEO?',
    a2: 'Setiap website dikembangkan dengan struktur SEO-friendly, performa optimal, dan siap dikembangkan untuk strategi SEO jangka panjang.',
    q3: 'Berapa lama waktu yang dibutuhkan untuk pembuatan website profesional?',
    a3: 'Waktu pengerjaan umumnya 2–6 minggu, tergantung scope proyek yang dikerjakan, jumlah halaman, dan kebutuhan integrasi sistem pendukungnya.',
    q4: 'Apakah website bisa dikembangkan untuk kebutuhan bisnis di masa depan?',
    a4: 'Website dirancang scalable sehingga mudah dikembangkan untuk fitur baru, integrasi sistem, dan pertumbuhan bisnis yang berkelanjutan di masa mendatang.',
    q5: 'Apakah Alur Kriya menyediakan maintenance dan preventive management website?',
    a5: 'Kami menyediakan layanan preventive management untuk memastikan website selalu aman, stabil, dan optimal sebelum masalah terjadi.',
    q6: 'Apakah bisa migrasi website lama ke sistem yang lebih modern?',
    a6: 'Kami melayani migrasi website, data, dan sistem ke teknologi yang lebih aman, cepat, dan efisien dengan meminimalisir waktu downtime tanpa mengganggu operasional bisnis.',
  },
  {
    slug: 'it-consulting',
    heading: 'IT Consulting',
    q1: 'Apa itu IT Consulting dan apa manfaatnya bagi bisnis?',
    a1: 'IT Consulting adalah layanan pendampingan strategis untuk membantu bisnis merencanakan, mengelola, dan mengoptimalkan teknologi agar selaras dengan tujuan bisnis dan operasional.',
    q2: 'Kapan perusahaan membutuhkan jasa IT Consulting?',
    a2: 'Perusahaan membutuhkan IT Consulting saat mengalami pertumbuhan bisnis, migrasi sistem, masalah performa IT, atau ingin meningkatkan efisiensi dan keamanan teknologi.',
    q3: 'Apa saja yang termasuk dalam layanan jasa IT Consulting?',
    a3: 'Layanan IT Consulting meliputi assessment sistem, perencanaan roadmap teknologi, rekomendasi arsitektur IT, optimasi infrastruktur, hingga manajemen risiko dan keamanan.',
    q4: 'Apakah IT Consulting cocok untuk perusahaan menengah dan B2B?',
    a4: 'Ya. IT Consulting sangat relevan bagi perusahaan menengah dan B2B untuk memastikan investasi teknologi tepat sasaran dan mendukung pertumbuhan jangka panjang.',
    q5: 'Berapa biaya jasa IT Consulting?',
    a5: 'Biaya IT Consulting bergantung pada ruang lingkup dan kompleksitas kebutuhan. Alur Kriya menyediakan IT Consulting Gratis untuk tahap awal analisis kebutuhan bisnis.',
    q6: 'Apa perbedaan IT Consulting dan IT Support?',
    a6: 'IT Consulting berfokus pada strategi dan perencanaan teknologi, sedangkan IT Support menangani masalah teknis harian. Keduanya saling melengkapi untuk pengelolaan IT yang optimal.',
  },
  {
    slug: 'data-system-migration',
    heading: 'Data & System Migration',
    q1: 'Apa itu Migrasi Data dan Sistem mengapa penting bagi bisnis?',
    a1: 'Migrasi Data dan Sistem adalah proses memindahkan data dan sistem dari platform lama ke sistem baru agar lebih aman, scalable, dan mendukung kebutuhan bisnis saat ini.',
    q2: 'Kapan waktu yang tepat untuk melakukan Migrasi Data dan Sistem?',
    a2: 'Perusahaan perlu melakukan migration saat upgrade sistem, berpindah ke cloud, mengganti aplikasi, atau ketika sistem lama sudah tidak efisien dan berisiko tinggi.',
    q3: 'Apa risiko jika Migrasi Data tidak dilakukan dengan benar?',
    a3: 'Risiko meliputi kehilangan data, downtime operasional, inkonsistensi sistem, hingga gangguan pada proses bisnis yang berdampak langsung pada produktivitas.',
    q4: 'Bagaimana proses Migrasi Data dan Sistem yang aman?',
    a4: 'Proses aman mencakup assessment awal, perencanaan migrasi, backup data, pengujian, serta validasi pasca-migrasi untuk memastikan data tetap utuh dan sistem berjalan normal.',
    q5: 'Apakah Migrasi Data dan Sistem bisa dilakukan tanpa downtime?',
    a5: 'Dalam banyak kasus, migration dapat dirancang dengan downtime minimal atau zero downtime menggunakan strategi bertahap dan parallel system deployment.',
    q6: 'Berapa biaya jasa Migrasi Data dan Sistem?',
    a6: 'Biaya bergantung pada volume data, kompleksitas sistem, dan target platform. Alur Kriya menyediakan analisis awal untuk menentukan skema migrasi yang paling efisien.',
  },
  {
    slug: 'cloud-hosting',
    heading: 'Cloud Hosting & Infrastructure',
    q1: 'Apa itu  Cloud Hosting dan Infrastructure?',
    a1: 'Cloud Hosting dan Infrastructure adalah layanan pengelolaan server dan infrastruktur berbasis cloud yang scalable, aman, dan siap mendukung pertumbuhan bisnis.',
    q2: 'Apa keunggulan layanan Cloud dibandingkan server konvensional?',
    a2: 'Cloud lebih fleksibel, mudah ditingkatkan, memiliki uptime tinggi, serta mengurangi biaya investasi infrastruktur fisik.',
    q3: 'Apakah layanan Cloud Hosting aman untuk data perusahaan?',
    a3: 'Cloud dilengkapi enkripsi data, firewall, monitoring, dan kontrol akses untuk menjaga keamanan dan kepatuhan data.',
    q4: 'Layanan Cloud hosting cocok untuk jenis bisnis apa?',
    a4: 'Cloud cocok untuk perusahaan menengah hingga enterprise yang membutuhkan performa stabil, skalabilitas tinggi, dan ketersediaan sistem 24/7.',
    q5: 'Apakah layanan Cloud bisa disesuaikan dengan kebutuhan bisnis?',
    a5: 'Infrastruktur cloud dapat dikonfigurasi sesuai kebutuhan aplikasi, traffic, dan pertumbuhan bisnis.',
    q6: 'Berapa biaya layanan Cloud Hosting dan Infrastructure?',
    a6: 'Biaya bergantung pada resource yang digunakan seperti CPU, storage, bandwidth, dan tingkat manajemen layanan.',
  },
  {
    slug: 'it-procurement-support',
    heading: 'IT Procurement & Support',
    q1: 'Apa itu IT Procurement & Support?',
    a1: 'IT Procurement & Support adalah layanan pengadaan perangkat IT dan dukungan teknis untuk memastikan operasional bisnis berjalan stabil dan efisien.',
    q2: 'Apa manfaat menggunakan jasa IT Procurement profesional?',
    a2: 'Layanan ini membantu memilih perangkat yang tepat, menekan biaya, dan memastikan kompatibilitas dengan sistem bisnis yang ada.',
    q3: 'Apa saja yang termasuk layanan IT Support?',
    a3: 'Layanan mencakup troubleshooting, maintenance sistem, monitoring, dan dukungan teknis harian untuk mencegah downtime.',
    q4: 'Apakah IT Procurement & Support cocok untuk perusahaan menengah?',
    a4: 'Layanan ini membantu perusahaan menengah mengelola IT secara profesional tanpa harus membangun tim internal besar.',
    q5: 'Bagaimana IT Procurement membantu efisiensi biaya?',
    a5: 'Dengan perencanaan yang tepat dan vendor terpercaya, perusahaan dapat menghindari pembelian berlebih dan menekan biaya jangka panjang.',
    q6: 'Berapa biaya jasa IT Procurement & Support?',
    a6: 'Biaya disesuaikan dengan skala kebutuhan, jenis perangkat, dan tingkat dukungan yang dibutuhkan, umumnya berbasis proyek atau kontrak layanan.',
  },
  {
    slug: 'saas-partners',
    heading: 'SaaS Partners',
    q1: 'Apa itu layanan SaaS Partners?',
    a1: 'SaaS Partners adalah layanan pendampingan dalam memilih, mengimplementasikan, dan mengelola aplikasi SaaS agar selaras dengan kebutuhan bisnis.',
    q2: 'Apa manfaat menggunakan SaaS Partners bagi perusahaan?',
    a2: 'Layanan ini membantu memastikan SaaS terintegrasi dengan sistem yang ada, lebih efisien, dan memberikan nilai maksimal bagi bisnis.',
    q3: 'SaaS Partners mencakup aplikasi apa saja?',
    a3: 'SaaS Partners mencakup CRM, ERP, HRIS, accounting, collaboration tools, dan aplikasi bisnis berbasis cloud lainnya.',
    q4: 'Bagaimana SaaS Partners membantu integrasi sistem?',
    a4: 'SaaS Partners memastikan integrasi antar aplikasi berjalan lancar melalui konfigurasi, API, dan sinkronisasi data yang tepat.',
    q5: 'Apakah SaaS Partners membantu pengelolaan biaya langganan?',
    a5: 'Layanan ini membantu mengontrol lisensi, menghindari pemborosan, dan mengoptimalkan biaya SaaS sesuai kebutuhan aktual.',
    q6: 'Berapa biaya jasa SaaS Partners?',
    a6: 'Biaya bergantung pada jumlah aplikasi, kompleksitas integrasi, dan tingkat dukungan yang dibutuhkan, umumnya berbasis proyek atau langganan.',
  },
];